## Contents<a id='3.1_Contents'></a>
* [2 Exploratory Data Analysis](#2_Exploratory_Data_Analysis)
  * [2.1 Introduction](#2.1_Introduction)
  * [2.2 Imports](#2.2-Imports)
  * [2.3 Load the data](#2.3-Load-the-data)
  * [2.4 Removing prefixes](#2.4-Removing-prefixes)
  * [2.5 Extracting portions of URL](#2.5-Extracting-portions-of-URL)
    * [2.5.1 Extracting host](#2.5.1-Extracting-host)
    * [2.5.2 Extracting the top level domain](#2.5.2-Extracting-the-top-level-domain)
  * [2.6 Feature Creation](#2.6-Feature-Creation)
    * [2.6.1 Calculating lengths](#2.6.1-Calculating-lengths)
      * [2.6.1.1 Calculating URL length](#2.6.1.1-Calculating-URL-length)
      * [2.6.1.2 Calculating host length](#2.6.1.2-Calculating-host-length)
      * [2.6.1.3 Calculating top level domain length](#2.6.1.3-Calculating-top-level-domain-length)
    * [2.6.2 URL containing IP address](#2.6.2-URL-containing-IP-address)
    * [2.6.3 Calculating Shannon entropy](#2.6.3-Calculating-Shannon-entropy)
      * [2.6.3.1 Calculating Shannon entropy for url](#2.6.3.1-Calculating-Shannon-entropy-for-url)
      * [2.6.3.2 Calculating Shannon entropy for ext_host](#2.6.3.2-Calculating-Shannon-entropy-for-ext_host)
      * [2.6.3.3 Calculating Shannon entropy for tlds](#2.6.3.3-Calculating-Shannon-entropy-for-tlds)
    * [2.6.4 Containing java script queries](#2.6.4-Containing-java-script-queries)
    * [2.6.5 Finding number-dot pattern](#2.6.5-Finding-number-dot-pattern)
      * [2.6.5.1 Number of number-dot pattern greater than two](#2.6.5.1-Number-of-number-dot-pattern-greater-than-two)
      * [2.6.5.2 Sum of entropy of number-dot pattern greater than two](#2.6.5.2-Sum-of-entropy-of-number-dot-pattern-greater-than-two)
    * [2.6.6 Capital letters in host](#2.6.6-Capital-letters-in-host)
    * [2.6.7 Capital letters in url](#2.6.7-Capital-letters-in-url)
    * [2.6.8 Calculating alphabet based ratios](#2.6.8-Calculating-alphabet-based-ratios)
      * [2.6.8.1 Calculating character to number ratio in url](#2.6.8.1-Calculating-character-to-number-ratio-in-url)
      * [2.6.8.2 Calculating character to special characters ratio in url](#2.6.8.2-Calculating-character-to-special-characters-ratio-in-url)
      * [2.6.8.3 Calculating character to number ratio in host](#2.6.8.3-Calculating-character-to-number-ratio-in-host)
      * [2.6.8.4 Calculating character to special characters ratio in host](#2.6.8.4-Calculating-character-to-special-characters-ratio-in-host)
    * [2.6.9 Detecting obfuscation](#2.6.9-Detecting-obfuscation)
      * [2.6.9.1 Detecting obfuscation in url](#2.6.9.1-Detecting-obfuscation-in-url)
      * [2.6.9.2 Detecting obfuscation in host](#2.6.9.2-Detecting-obfuscation-in-host)
      * [2.6.9.3 Calculating obfuscation entropy in url](#2.6.9.3-Calculating-obfuscation-entropy-in-url)
      * [2.6.9.3 Calculating obfuscation entropy in host](#2.6.9.3-Calculating-obfuscation-entropy-in-host)
    * [2.6.10 Calculating entropy of random substring](#2.6.10-Calculating-entropy-of-random-substring)
      * [2.6.10.1 Calculating entropy of random substring in url](#2.6.10.1-Calculating-entropy-of-random-substring-in-url)
      * [2.6.10.2 Calculating entropy of random substring in host](#2.6.10.2-Calculating-entropy-of-random-substring-in-host)
    * [2.6.11 The number of individual special chracters](#2.6.11-The-number-of-individual-special-chracters)
      * [2.6.11.1 Number of hypens](#2.6.11.1-Number-of-hypens)
      * [2.6.11.2 Number of underscores](#2.6.11.2-Number-of-underscores)
      * [2.6.11.3 Number of semicolons](#2.6.11.3-Number-of-semicolons)
      * [2.6.11.4 Number of equal signs](#2.6.11.4-Number-of-equal-signs)
      * [2.6.11.5 Number of plus signs](#2.6.11.5-Number-of-plus-signs)
    * [2.6.12 Segments in host](#2.6.12-Segments-in-host)
      * [2.6.12.1 Number of segments in host](#2.6.12.1-Number-of-segments-in-host)
      * [2.6.12.2 Total entropy of segments in host](#2.6.12.2-Total-entropy-of-segments-in-host)
    * [2.6.12 Applying Similarity Index to top level domain](#2.6.12-Applying-Similarity-Index-to-top-level-domain)
    * [2.6.13 Probability distribution of special characters](#2.6.13-Probability-distribution-of-special-characters)
    * [2.6.14 Frequent words in legitimats/phishing URLs](#2.6.14-Frequent-words-in-legitimats/phishing-URLs)
      * [2.6.14.1 Count of the words that only appear in phishing urls](#2.6.14.1-Count-of-the-words-that-only-appear-in-phishing-urls)
      * [2.6.14.2 Count of the words that only appear in legitimate/phishing urls](#2.6.14.2-Count-of-the-words-that-only-appear-in-legitimate/phishing-urls)
      * [2.6.14.3 Sum of entropy of the words that appeared in legitimate/phishing urls](#2.6.14.3-Sum-of-entropy-of-the-words-that-appeared-in-legitimate/phishing-urls)
      * [2.6.14.4 Count of the words that only appear in phishing ext_host](#2.6.14.4-Count-of-the-words-that-only-appear-in-phishing-ext_host)
      * [2.6.15.5 Sum of entropy of the words that appeared in phishing ext_host](#2.6.15.5-Sum-of-entropy-of-the-words-that-appeared-in-phishing-ext_host)
      * [2.6.14.6 Count of the words that only appear in legitimate/phishing ext_host](#2.6.14.6-Count-of-the-words-that-only-appear-in-legitimate/phishing-ext_host)
      * [2.6.14.7 Sum of entropy of the words that appeared in legitimate/phishing ext_host](#2.6.14.7-Sum-of-entropy-of-the-words-that-appeared-in-legitimate/phishing-ext_host)
    * [2.6.15 Using NLTK corpus](#2.6.15-Using-NLTK-corpus)
      * [2.6.15.1 Common English words in url](#2.6.15.1-Common-English-words-in-url)
      * [2.6.15.2 Entropy of common English words in url](#2.6.15.2-Entropy-of-common-English-words-in-url)
      * [2.6.15.3 Common English words in host](#2.6.15.3-Common-English-words-in-host)
      * [2.6.15.4 Entropy of common English words in host](#2.6.15.4-Entropy-of-common-English-words-in-host)
  * [2.7 Saving the file](#2.7-Saving-the-file)
  * [2.8 TF-IDF](#2.8-TF-IDF)

# 2.1 Introduction

As we have seen previously, our dataset doesn't have significant missing values or inconsistencies that need to be addressed. But it lacks features that could directly aid in predicting phishing URLs. Therefore, we will focus on feature engineering to create relevant predictors.

# 2.2 Imports

In [5]:
import pandas as pd
import numpy as np
import re
import math
from math import log2
from collections import Counter

import nltk
from nltk.corpus import words

from fuzzywuzzy import fuzz
from fuzzywuzzy import process

from tqdm import tqdm
from functools import lru_cache

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

# 2.3 Load the data

In [7]:
df = pd.read_csv('../data/processed/url_new_cleaned.csv', index_col=0)

In [8]:
df.head()

                                       url  status
0  0000111servicehelpdesk.godaddysites.com       0
1     000011accesswebform.godaddysites.com       0
2                             00003.online       0
3      0009servicedeskowa.godaddysites.com       0
4                     000n38p.wcomhost.com       0

In [9]:
# Enables the progress bar for operations in pandas, allowing visual tracking of the process progress using tqdm.
tqdm.pandas()

# 2.4 Removing prefixes

This step is performed to make the observations more balanced in terms of content. As the urls are scraped from the internet there might be some errors during the scraping process that might have caused the loss of https:// or www from the beginning. As we want to make our predictive model robust we do not want to bias our prediction based on the presence of the https:// or www.

In [12]:
# Removing prefixes (http://, https://)
df['url'] = df['url'].str.replace(r'^(http://|https://|https|http)', '', regex=True)

In [13]:
# Removing '.' 
df['url'] = df['url'].str.lstrip('.')

In [14]:
# Removing 'www.' prefix explicitly
df['url'] = df['url'].str.replace(r'^(www|www1|www2|www3|www4)', '', regex=True)

In [15]:
df['url'] = df['url'].str.lstrip('.')

In [16]:
df[(df['url'].str.startswith('http', 'www')) & (df.status == 1)]

                                                  url  status
697726                    http2.github.io/http2-spec/       1
697731  httpd.apache.org/docs/2.4/programs/httpd.html       1

In [17]:
df[(df['url'].str.startswith('http', 'www')) & (df.status == 0)]

                                                      url  status
28727   httpdmcaremoval-9742697748.info-protech.be/con...       0
29134                   httpsservices.runescape.com-n.ru/       0
29159   httpdmcaremoval-2883901933.info-protech.be/con...       0
29880                  httpsservices.runescape.com-no.ru/       0
29986                  httpsservices.runescape.com-ov.ru/       0
...                                                   ...     ...
716646  https-impots-gouve-fr.com/impots.gouv/Impots-e...       0
723239  https.www.payypal.com.resolution.center.limita...       0
723240  https.www.payypal.com.resolution.center.limita...       0
723241  https.www.payppal.com.resolution.center.limita...       0
723242  https.www.payppal.com.resolution.center.limita...       0

[73 rows x 2 columns]

In [18]:
df[(df['url'].str.startswith('/'))]

                                                     url  status
50759  /forum.square-enix.com-i.cc/ffxiv/threads/417237/       0

In [19]:
df['url'] = df['url'].str.strip().str.strip('/')

In [20]:
df[(df['url'].str.startswith('/'))]

Empty DataFrame
Columns: [url, status]
Index: []

# 2.5 Extracting portions of URL

Some of the urls contains path and some do not. So, we want to extract the host part (domain, subdomain, top level domain) that must be common on every url and generate some feature based on the host part to make the model more generalized on unseen data.

### 2.5.1 Extracting host

In [24]:
# Extracted the host part (containing domain, subdomian, tld, port etc.)
df['ext_host'] = df['url'].str.split('/').str[0]

In [25]:
df.tail()

,url,status,ext_host
807612,zzufg.com,0,zzufg.com
807613,zzu.li,0,zzu.li
807614,zzz.co.uk,0,zzz.co.uk
807615,zzzoolight.co.za,0,zzzoolight.co.za
807616,zzzoolight.co.za0-i-fdik.000webhostapp.com,0,zzzoolight.co.za0-i-fdik.000webhostapp.com

In [26]:
def host_end(url):
    '''To find any trailing dots in the extracted host'''
    return url.endswith('.')

In [27]:
df[df['ext_host'].apply(host_end)]

,url,status,ext_host
12297,ijhriogjef2831g.club.,0,ijhriogjef2831g.club.
166741,n-change.net.,0,n-change.net.
167617,summa.cash.,0,summa.cash.
212222,ssl-allegro.comuf.com./allegro.html,0,ssl-allegro.comuf.com.
215993,update.visaeurope.com.card.verified.us.delphia...,0,update.visaeurope.com.card.verified.us.delphia...
259054,bkent.net./Doc/simple5.htm,1,bkent.net.
664473,syydettyjendatumm.brockalumni.com.,0,syydettyjendatumm.brockalumni.com.
664474,komunistycznymi.afshinnejad.com.,0,komunistycznymi.afshinnejad.com.
664475,nubeculaminor-blossgestellter.f-oaks.com.,0,nubeculaminor-blossgestellter.f-oaks.com.
664476,asseveravronnakiewietsblom.shopdentalsupply.com.,0,asseveravronnakiewietsblom.shopdentalsupply.com.
664477,pseudoalcaligenes.nhconstruction.com.,0,pseudoalcaligenes.nhconstruction.com.
664478,perverselymotorbikes.shopmedicalgloves.com.,0,perverselymotorbikes.shopmedicalgloves.com.
669609,gianlucaboezio.it./nJHbj0266b,0,gianlucaboezio.it.
669650,gianlucaboezio.it./nJHbj0266b?bVNhynB=AiGSHMqkUH,0,gianlucaboezio.it.
682658,250sb.com./jynvmx,0,250sb.com.
742457,asan-unes.firebaseapp.com.,0,asan-unes.firebaseapp.com.
763411,hantansouloire.com.,0,hantansouloire.com.
779512,network.,0,network.

In [28]:
def remove_trailing_dots(url):
    '''A function to remove any trailing dots in the extracted domain'''
    return url.rstrip('.')
df['ext_host'] = df['ext_host'].apply(remove_trailing_dots)

In [29]:
df[df['ext_host'].apply(host_end)]

Empty DataFrame
Columns: [url, status, ext_host]
Index: []

In [30]:
df.ext_host.isnull().sum()

0

In [31]:
df['ext_host'] = df['ext_host'].astype(str)

### 2.5.2 Extracting the top level domain

In [33]:
# Extracting the top level domain
def tld_url(url):
    '''A function to split a string based on dot and extracting the last part'''
    parts = url.split('.')
    return parts[-1] if len(parts) > 0 else None
df['tlds'] = df['ext_host'].apply(tld_url)

# 2.6 Feature Creation

## 2.6.1 Calculating lengths

#### 2.6.1.1 Calculating URL length

In [37]:
df['len_url'] = df['url'].apply(len)

#### 2.6.1.2 Calculating host length

In [39]:
df['len_host'] = df['ext_host'].apply(len)

#### 2.6.1.3 Calculating top level domain length

In [41]:
# Converting all entries in the 'tlds' column to strings and handling NaN values
df['tlds'] = df['tlds'].fillna('').astype(str)
df['len_tld'] = df['tlds'].apply(len)

## 2.6.2 URL containing IP address

In [43]:
def contains_ip(url):
    '''A function to find IP address pattern in string'''
    
    # Regex to match an IPv4 address
    ipv4_pattern = r'(\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b)'
    
    # Regex to match an IPv6 address
    ipv6_pattern = r'(\[[0-9a-fA-F:]+\])'
    
    # Combining both IPv4 and IPv6 address
    combined_pattern = rf'{ipv4_pattern}|{ipv6_pattern}'
    
    return bool(re.search(combined_pattern, url))

In [44]:
df['contains_ip'] = df['url'].apply(contains_ip)

In [45]:
df['contains_ip'] = df['contains_ip'].astype(int)

## 2.6.3 Calculating Shannon entropy

Shannon entropy is named after Claude Shannon, a famous mathematician. Shannon originally developed the concept in 1948 to measure the richness and evenness of plant and animal species. 

It's a statistical quantifier used in characterization of complex process. In information theory, the entropy of a random variable quantifies the average level of uncertainty or information associated with the variable's potential states or possible outcomes. This measures the expected amount of information needed to describe the state of the variable, considering the distribution of probabilities across all potential states. 

Shannon entropy measures the uncertainty or information content in a random variable. If all outcomes are equally likely, the entropy is high (maximum uncertainty). If one outcome is highly likely, the entropy is low (less uncertainty).

The Shannon entropy H(X) of a random variable X is defined as the negative sum of the probabilities P(xi) of each possible outcome xi, multiplied by the logarithm (to base b) of that probability.

Entropy can be applied to detect phishing URLs by measuring the uncertainty in character distributions. Phishing URLs often include unusual patterns to mimic legitimate sites, leading to higher entropy.

#### 2.6.3.1 Calculating Shannon entropy for url

In [49]:
def calculate_entropy(url):
    '''Defining the entropy calculation function'''
    
    # Calculating the frequency of each character
    probabilities = [float(url.count(char)) / len(url) for char in set(url)]
    
    # Computing Shannon entropy
    # The base-2 logarithm is used in Shannon entropy calculations because the measure is typically expressed in terms of bits (binary information)
    # The base-2 log of a probability indicates how many binary bits are required to encode an event of that probability.
    # This aligns with how digital systems (e.g., computers) store and process information.
    entropy = -sum([p * np.log2(p) for p in probabilities])
    return entropy

In [50]:
df['url_entropy'] = df['url'].apply(calculate_entropy)

#### 2.6.3.2 Calculating Shannon entropy for ext_host

In [52]:
df['host_entropy'] = df['ext_host'].apply(calculate_entropy)

#### 2.6.3.3 Calculating Shannon entropy for tlds

In [54]:
df['tld_entropy'] = df['tlds'].apply(calculate_entropy)

## 2.6.4 Containing java script queries

JavaScript-related query parameters in URLs often serve specific functions. Parameters like callback, load, or js are often used for loading dynamic JavaScript resources or APIs. Query strings like query might collect search keywords or other data. Parameters may point to .js files directly. While these actions are done for legitimate purpose but they can also be mimicked to legitimate services to trick users. Manipulated to inject malicious scripts or redirect to unauthorized resources.

Phishing URLs often include overly complex or meaningless query strings. While legitimate URLs tend to use structured, predictable, and meaningful queries.

High entropy in query parameters might indicate randomization or obfuscation, common in phishing URLs to bypass detection systems.

Shannon entropy is a measure of uncertainty or variability in a system, based on the probabilities of different situations. It was developed by Claude Shannon in 1948 to measure the richness and evenness of plant and animal species.

In [57]:
query_pattern = r'\?([^=]+)=([^&]+)'                      # Detects query parameters
fragment_pattern = r'#([^/]+)'                            # Detects fragment identifiers
js_param_pattern = r'[?&](js|callback|load|query)=[^&]+'  # Detects JavaScript-like parameters
js_file_pattern = r'\.js$'                                # Detects .js in the URL path

# Combine all patterns with | (alternation)
combined_pattern = f'{query_pattern}|{fragment_pattern}|{js_param_pattern}|{js_file_pattern}'

In [58]:
def check_js(url):
    '''A Function to check for JavaScript-related patterns in the URL'''
    return bool(re.search(combined_pattern, url))

In [59]:
df['has_js'] = df['url'].apply(check_js)

In [60]:
df['has_js'] = df['has_js'].astype(int)

In [61]:
# Calculating the entropy of the all the patterns found in a url

In [62]:
def extract_matches(url):
    '''A function to extract pre defined patterns'''
    matches = re.findall(combined_pattern, url)
    return matches if matches else []

In [63]:
def calculate_entropy(matches):
    '''A function to join all matches found in previous step and find the total shanon entropy'''
    if not matches:
        return 0  # No matches, no entropy
    combined = ''.join(''.join(match) for match in matches)  # Flattenning the list of tuples into a string
    freq = {char: combined.count(char) for char in set(combined)}  # Counting character frequency
    total = len(combined)  # Total characters
    entropy = -sum((count / total) * log2(count / total) for count in freq.values())  # Shannon entropy
    return entropy

In [64]:
df['query_js'] = df['url'].apply(extract_matches)  # Store matched patterns as a list
df['js_entropy'] = df['query_js'].apply(calculate_entropy)  # Calculate entropy of the matches

## 2.6.5 Finding number-dot pattern

#### 2.6.5.1 Number of number-dot pattern greater than two

In [67]:
def find_long_number_dot_patterns(url):
    '''A function using regex to match number-and-dot patterns >= 3'''
    pattern = r'(\d+(\.\d+)+)'
    matches = re.findall(pattern, url)
    
    # Extracting only the patterns and filtering based on length
    filtered_matches = [(match[0], len(match[0])) for match in matches if len(match[0]) > 2]
    return filtered_matches

In [68]:
df['dotnum_pat_3'] = df['url'].apply(find_long_number_dot_patterns)

In [69]:
# Create a column that stores the number of such patterns found in each URL
df['num_pat_3'] = df['dotnum_pat_3'].apply(lambda x: len(x))

#### 2.6.5.2 Sum of entropy of number-dot pattern greater than two

In [71]:
def cal_word_entropy(matches):
    '''A function to calculate the sum of entropy of all list items'''
    if not matches:
        return 0
        
    # Use only the first element of each tuple (the matched pattern)
    patterns = [match[0] for match in matches]
    total_entropy = sum(calculate_entropy(pattern) for pattern in patterns)
    return total_entropy

In [72]:
df['pat_3_entropy'] = df['dotnum_pat_3'].progress_apply(cal_word_entropy)

100%|█████████████████████████████████████████████████████████████████████| 807617/807617 [00:00<00:00, 1057936.89it/s]

In [73]:
df

,url,status,ext_host,tlds,len_url,len_host,len_tld,contains_ip,url_entropy,host_entropy,tld_entropy,has_js,query_js,js_entropy,dotnum_pat_3,num_pat_3,pat_3_entropy
0,0000111servicehelpdesk.godaddysites.com,0,0000111servicehelpdesk.godaddysites.com,com,39,39,3,0,4.045286,4.045286,1.584963,0,[],0.0,[],0,0.0
1,000011accesswebform.godaddysites.com,0,000011accesswebform.godaddysites.com,com,36,36,3,0,3.974938,3.974938,1.584963,0,[],0.0,[],0,0.0
2,00003.online,0,00003.online,online,12,12,6,0,2.751629,2.751629,2.251629,0,[],0.0,[],0,0.0
3,0009servicedeskowa.godaddysites.com,0,0009servicedeskowa.godaddysites.com,com,35,35,3,0,3.943289,3.943289,1.584963,0,[],0.0,[],0,0.0
4,000n38p.wcomhost.com,0,000n38p.wcomhost.com,com,20,20,3,0,3.546439,3.546439,1.584963,0,[],0.0,[],0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807612,zzufg.com,0,zzufg.com,com,9,9,3,0,2.947703,2.947703,1.584963,0,[],0.0,[],0,0.0
807613,zzu.li,0,zzu.li,li,6,6,2,0,2.251629,2.251629,1.000000,0,[],0.0,[],0,0.0
807614,zzz.co.uk,0,zzz.co.uk,uk,9,9,2,0,2.419382,2.419382,1.000000,0,[],0.0,[],0,0.0
807615,zzzoolight.co.za,0,zzzoolight.co.za,za,16,16,2,0,3.077820,3.077820,1.000000,0,[],0.0,[],0,0.0
807616,zzzoolight.co.za0-i-fdik.000webhostapp.com,0,zzzoolight.co.za0-i-fdik.000webhostapp.com,com,42,42,3,0,4.145543,4.145543,1.584963,0,[],0.0,[],0,0.0

In [74]:
df[(df.pat_3_entropy != 0)]

,url,status,ext_host,tlds,len_url,len_host,len_tld,contains_ip,url_entropy,host_entropy,tld_entropy,has_js,query_js,js_entropy,dotnum_pat_3,num_pat_3,pat_3_entropy
29,0331.16mb.com,0,0331.16mb.com,com,13,13,3,0,3.085055,3.085055,1.584963,0,[],0.0,"[(0331.16, 7)]",1,2.235926
46,08782949.624dgns34gh.pw,0,08782949.624dgns34gh.pw,pw,23,23,2,0,3.882045,3.882045,1.000000,0,[],0.0,"[(08782949.624, 12)]",1,2.918296
56,0947.16mb.com,0,0947.16mb.com,com,13,13,3,0,3.392747,3.392747,1.584963,0,[],0.0,"[(0947.16, 7)]",1,2.807355
76,10000587845458.16mb.com,0,10000587845458.16mb.com,com,23,23,3,0,3.414441,3.414441,1.584963,0,[],0.0,"[(10000587845458.16, 17)]",1,2.822182
78,1000265854000295.16mb.com,0,1000265854000295.16mb.com,com,25,25,3,0,3.433270,3.433270,1.584963,0,[],0.0,"[(1000265854000295.16, 19)]",1,2.865577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807401,zmcynup10.000webhostapp.com,0,zmcynup10.000webhostapp.com,com,27,27,3,0,3.986188,3.986188,1.584963,0,[],0.0,"[(10.000, 6)]",1,1.251629
807419,zoejurgensen15.000webhostapp.com,0,zoejurgensen15.000webhostapp.com,com,32,32,3,0,4.202820,4.202820,1.584963,0,[],0.0,"[(15.000, 6)]",1,1.792481
807540,zttwqerui12345678909865432345.000webhostapp.com,0,zttwqerui12345678909865432345.000webhostapp.com,com,47,47,3,0,4.596726,4.596726,1.584963,0,[],0.0,"[(12345678909865432345.000, 24)]",1,3.323935
807579,zxcvasdf1234.000webhostapp.com,0,zxcvasdf1234.000webhostapp.com,com,30,30,3,0,4.348394,4.348394,1.584963,0,[],0.0,"[(1234.000, 8)]",1,2.405639
807580,zxcwr11111.000webhostapp.com,0,zxcwr11111.000webhostapp.com,com,28,28,3,0,3.865765,3.865765,1.584963,0,[],0.0,"[(11111.000, 9)]",1,1.351644

## 2.6.6 Capital letters in host

In [76]:
def count_capital_letters(url):
    '''A function to find all capital letters using a regex'''
    return len(re.findall(r'[A-Z]', url))

In [77]:
df['host_len_capital'] = df['ext_host'].apply(count_capital_letters)

In [78]:
def ratio_capital(len_capital, ext_host):
    '''A function to find the ratio of capital letters'''
    if len_capital == 0:
        return 0
    else:
        return len_capital / len(ext_host)

In [79]:
df['host_ratio_capital'] = df.apply(lambda x: ratio_capital(x['host_len_capital'], x['ext_host']), axis=1)

## 2.6.7 Capital letters in url

In [81]:
df['url_len_capital'] = df['url'].apply(count_capital_letters)

In [82]:
df['url_ratio_capital'] = df.apply(lambda x: ratio_capital(x['url_len_capital'], x['url']), axis=1)

## 2.6.8 Calculating alphabet based ratios

#### 2.6.8.1 Calculating character to number ratio in url

In [85]:
def calculate_char_number_ratio(url):
    '''A function to calculate char to number ratio'''
    
    chars = sum(x.isalpha() for x in url)
    digits = sum(x.isdigit() for x in url)
    
    # Avoiding division by zero, return a ratio of 0 if no digits found
    return chars / digits if digits != 0 else 0

In [86]:
df['url_char_num_ratio'] = df['url'].apply(calculate_char_number_ratio)

#### 2.6.8.2 Calculating character to special characters ratio in url

In [88]:
def calculate_spe_char_ratio(url):
    '''A function to calculate special char ratio'''
    
    chars = sum(x.isalpha() for x in url)
    digits = sum(x.isdigit() for x in url)
    char_digit = chars + digits
    special_excluding_digits = len(url) - char_digit
    
    # Avoiding division by zero, return a ratio of 0 if no digits found
    return char_digit / special_excluding_digits if special_excluding_digits != 0 else 0

In [89]:
df['url_spe_char_ratio'] = df['url'].apply(calculate_spe_char_ratio)

#### 2.6.8.3 Calculating character to number ratio in host

In [91]:
df['host_char_num_ratio'] = df['ext_host'].apply(calculate_char_number_ratio)

#### 2.6.8.4 Calculating character to special characters ratio in host

In [93]:
df['host_spe_char_ratio'] = df['ext_host'].apply(calculate_spe_char_ratio)

## 2.6.9 Detecting obfuscation

#### 2.6.9.1 Detecting obfuscation in url

In [96]:
def detect_obfuscation(url):
    '''# A function to detect obfuscation'''
    obfuscation_patterns = [
        # URL encoding
        r'%[0-9a-fA-F]{2}',  # matches any hexadecimal digit (0-9, a-f, or A-F).
                             # {2} specifies that exactly 2 hexadecimal characters should follow %
                             # https://example.com/page%20name (contains %20, which is URL encoding for a space).
                             # https://example.com/file%3Fquery (contains %3F, which is URL encoding for ?).
        
        # Hexadecimal
        r'[a-fA-F0-9]{4,}',  # This pattern identifies long sequences of hexadecimal characters (4 or more). 
                             # Matches any hexadecimal digit (0-9, a-f, or A-F).
                             # https://example.com/file/123abc (contains 123abc, a hexadecimal string).
    ]
    # Checks if any of the obfuscation patterns match
    obfuscation_detected = any(re.search(pattern, url) for pattern in obfuscation_patterns)
    return 0 if obfuscation_detected else 1  # 0 for obfuscated, 1 for not obfuscated

In [97]:
df['url_obfuscation_status'] = df['url'].apply(detect_obfuscation)

### 2.6.9.2 Detecting obfuscation in host

In [99]:
df['host_obfuscation_status'] = df['ext_host'].apply(detect_obfuscation)

#### 2.6.9.3 Calculating obfuscation entropy in url

In [101]:
def calculate_entropy(obfuscated_part):
    '''A function to calculate the sum of entropy of obfuscated parts'''
    
    if not obfuscated_part:
        return 0
        
    # Counting frequency of each character
    frequencies = {char: obfuscated_part.count(char) for char in set(obfuscated_part)}
    total = len(obfuscated_part)
    
    # Calculating shannon entropy
    entropy = -sum((freq / total) * np.log2(freq / total) for freq in frequencies.values())
    return entropy

In [102]:
def detect_obfuscation_entropy(url):
    '''A function to find obfuscated patterns and find the sum of their entropy'''
    obfuscation_patterns = [
        r'%[0-9a-fA-F]{2}',  
        r'[a-fA-F0-9]{4,}',  
    ]
    obfuscated_parts = []
    for pattern in obfuscation_patterns:
        obfuscated_parts.extend(re.findall(pattern, url))
    obfuscated_parts = ''.join(obfuscated_parts)  # Combinning all matched parts
    
    # Calculating entropy for the obfuscated parts
    return calculate_entropy(obfuscated_parts)

In [103]:
df['obfuscation_entropy_url'] = df['url'].apply(detect_obfuscation_entropy)

#### 2.6.9.4 Calculating obfuscation entropy in host

In [105]:
df['obfuscation_entropy_host'] = df['ext_host'].apply(detect_obfuscation_entropy)

## 2.6.10 Calculating entropy of random substring

#### 2.6.10.1 Calculating entropy of random substring in url

In [108]:
def find_random_substrings(url):
    '''A function to find random alphanumeric combination of 3 or more characters in URL'''
    
    # Regex for long random alphanumeric substrings (threshold of 3 or more characters)
    random_pattern = re.compile(r'[a-zA-Z0-9]{3,}') 
    matches = random_pattern.findall(url)
    return matches

In [109]:
df['url_random_substrings'] = df['url'].apply(find_random_substrings)

In [110]:
def cal_substring_entropy(substrings):
    '''A function to calculate the total entropy of a list of strings'''
    if not substrings:
        return 0
    total_entropy = sum(calculate_entropy(sub) for sub in substrings)
    return total_entropy

In [111]:
df['url_sub_entropy'] = df['url_random_substrings'].apply(cal_substring_entropy)

#### 2.6.10.2 Calculating entropy of random substring in host

In [113]:
# Finding random alphanumeric substring of 3 or more characters in ext_host
df['host_random_substrings'] = df['ext_host'].apply(find_random_substrings)

In [114]:
df['host_sub_entropy'] = df['host_random_substrings'].apply(cal_substring_entropy)

## 2.6.11 The number of individual special chracters

#### 2.6.11.1 Number of hypens

In [117]:
def count_hypens(url):
    return url.count('-')
df['n_hypens'] = df['url'].apply(count_hypens)

#### 2.6.11.2 Number of underscores

In [119]:
def count_uscore(url):
    return url.count('_')
df['n_uscores'] = df['url'].apply(count_uscore)

#### 2.6.11.3 Number of semicolons

In [121]:
def count_semicolon(url):
    return url.count(';')
df['n_semicolon'] = df['url'].apply(count_semicolon)

#### 2.6.11.4 Number of equal signs

In [123]:
def count_equsign(url):
    return url.count('=')
df['n_equal_sign'] = df['url'].apply(count_equsign)

#### 2.6.11.5 Number of plus signs

In [125]:
def count_plus_sign(url):
    return url.count('+')
df['n_plus_sign'] = df['url'].apply(count_plus_sign)

## 2.6.12 Segments in host

#### 2.6.12.1 Number of segments in host

In [128]:
df['num_segments_host'] = df['ext_host'].apply(lambda x: len(x.split('.')))

#### 2.6.12.2 Total entropy of segments in host

In [130]:
def host_segment(url):
    '''A function to segment a string by dot'''
    segments = url.split('.')
    return segments

In [131]:
df['host_segment_dot'] = df['ext_host'].apply(host_segment)

In [132]:
df['host_segment_entropy'] = df['host_segment_dot'].progress_apply(cal_substring_entropy)

100%|███████████████████████████████████████████████████████████████████████| 807617/807617 [00:28<00:00, 28269.90it/s]

## 2.6.12 Applying Similarity Index to top level domain

In [134]:
# A pandas DataFrame containing legitimate urls extracted from wikipedia
df_tlds_wiki = pd.read_csv('../data/processed/tlds_wiki.csv', index_col=0)

In [135]:
df_tlds_wiki.head()

  First Column
0          com
1          org
2          net
3          int
4          edu

In [136]:
df_tlds_wiki.isnull().sum()

First Column    1
dtype: int64

In [137]:
df_tlds_wiki = df_tlds_wiki.dropna()

In [138]:
df_tlds_wiki.dtypes

First Column    object
dtype: object

In [139]:
# Check for rows where 'tlds' contains ':' or is empty
mask = df_tlds_wiki['First Column'].str.contains(':', na=False) | df_tlds_wiki['First Column'].str.strip().eq('')

# Display rows that satisfy the condition
filtered_df = df_tlds_wiki[mask]
filtered_df

Empty DataFrame
Columns: [First Column]
Index: []

In [140]:
df['tlds'] = df['tlds'].astype(str)

In [141]:
tld_list = df_tlds_wiki['First Column'].tolist()

<b>Levenshtein distance</b> (also known as edit distance) measures how many operations (insertions, deletions, or substitutions) are needed to convert one string into another.

Fuzzy string matching determines how "similar" two strings are rather than requiring them to be identical. The process.extractOne function internally uses fuzzy string matching algorithms based on the Levenshtein Distance.

The @lru_cache(maxsize=None) decorator in Python is a tool for caching function results. It comes from the functools module and is particularly useful for optimizing expensive or frequently called functions by storing (or "memoizing") their results so that subsequent calls with the same arguments can return the cached value instead of recalculating it.

In [144]:
@lru_cache(maxsize=None)

def calculate_similarity_fuzzy_cached(tld):
    '''A function to calculate the similarity index'''

    # Checks if tld is missing or if it is an empty/whitespace string).
    if pd.isna(tld) or str(tld).strip() == '':
        return 0
        
    # process.extractOne returns a tuple like (best_match_string, similarity_score)    
    best_match = process.extractOne(tld, tuple(tld_list))
    return best_match[1] if best_match else 0

In [145]:
df['tld_fuzzy_score'] = df['tlds'].progress_apply(calculate_similarity_fuzzy_cached)

 82%|███████████████████████████████████████████████████████████▏            | 663461/807617 [01:01<00:15, 9592.15it/s]WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: ':']
100%|████████████████████████████████████████████████████████████████████████| 807617/807617 [01:28<00:00, 9098.64it/s]

## 2.6.13 Probability distribution of special characters

In [147]:
def calculate_special_char_prob(url, target_chars):
    '''A function to calculate the probability distribution of specific characters in a URL'''
    
    if not isinstance(url, str) or len(url) == 0:
        return {char: 0 for char in target_chars}
    
    # Counting occurrences of each character in the URL
    char_count = Counter(url)
    
    # Total number of characters in the URL
    total_chars = len(url)
    
    # Calculating probabilities for the target characters
    probabilities = {char: char_count[char] / total_chars for char in target_chars}
    
    return probabilities

In [148]:
# List of target characters
target_chars = ['-', '.', '@', ':', '=', '_', '&', '#', '!', '+']

# Appling the function to calculate probabilities for each URL
df['special_char_probabilities'] = df['url'].apply(lambda x: calculate_special_char_prob(x, target_chars))

In [149]:
df

,url,status,ext_host,tlds,len_url,len_host,len_tld,contains_ip,url_entropy,host_entropy,...,n_hypens,n_uscores,n_semicolon,n_equal_sign,n_plus_sign,num_segments_host,host_segment_dot,host_segment_entropy,tld_fuzzy_score,special_char_probabilities
0,0000111servicehelpdesk.godaddysites.com,0,0000111servicehelpdesk.godaddysites.com,com,39,39,3,0,4.045286,4.045286,...,0,0,0,0,0,3,"[0000111servicehelpdesk, godaddysites, com]",8.032136,100,"{'-': 0.0, '.': 0.05128205128205128, '@': 0.0,..."
1,000011accesswebform.godaddysites.com,0,000011accesswebform.godaddysites.com,com,36,36,3,0,3.974938,3.974938,...,0,0,0,0,0,3,"[000011accesswebform, godaddysites, com]",8.012840,100,"{'-': 0.0, '.': 0.05555555555555555, '@': 0.0,..."
2,00003.online,0,00003.online,online,12,12,6,0,2.751629,2.751629,...,0,0,0,0,0,2,"[00003, online]",2.973557,100,"{'-': 0.0, '.': 0.08333333333333333, '@': 0.0,..."
3,0009servicedeskowa.godaddysites.com,0,0009servicedeskowa.godaddysites.com,com,35,35,3,0,3.943289,3.943289,...,0,0,0,0,0,3,"[0009servicedeskowa, godaddysites, com]",8.137511,100,"{'-': 0.0, '.': 0.05714285714285714, '@': 0.0,..."
4,000n38p.wcomhost.com,0,000n38p.wcomhost.com,com,20,20,3,0,3.546439,3.546439,...,0,0,0,0,0,3,"[000n38p, wcomhost, com]",6.463048,100,"{'-': 0.0, '.': 0.1, '@': 0.0, ':': 0.0, '=': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807612,zzufg.com,0,zzufg.com,com,9,9,3,0,2.947703,2.947703,...,0,0,0,0,0,2,"[zzufg, com]",3.506891,100,"{'-': 0.0, '.': 0.1111111111111111, '@': 0.0, ..."
807613,zzu.li,0,zzu.li,li,6,6,2,0,2.251629,2.251629,...,0,0,0,0,0,2,"[zzu, li]",1.918296,90,"{'-': 0.0, '.': 0.16666666666666666, '@': 0.0,..."
807614,zzz.co.uk,0,zzz.co.uk,uk,9,9,2,0,2.419382,2.419382,...,0,0,0,0,0,3,"[zzz, co, uk]",2.000000,90,"{'-': 0.0, '.': 0.2222222222222222, '@': 0.0, ..."
807615,zzzoolight.co.za,0,zzzoolight.co.za,za,16,16,2,0,3.077820,3.077820,...,0,0,0,0,0,3,"[zzzoolight, co, za]",4.646439,90,"{'-': 0.0, '.': 0.125, '@': 0.0, ':': 0.0, '='..."
807616,zzzoolight.co.za0-i-fdik.000webhostapp.com,0,zzzoolight.co.za0-i-fdik.000webhostapp.com,com,42,42,3,0,4.145543,4.145543,...,2,0,0,0,0,5,"[zzzoolight, co, za0-i-fdik, 000webhostapp, com]",11.334163,100,"{'-': 0.047619047619047616, '.': 0.09523809523..."

In [150]:
# Creating separate columns for each target character's probability
char_prob_df = df['special_char_probabilities'].apply(pd.Series).fillna(0)

# Concatenating with the original DataFrame
df = pd.concat([df, char_prob_df], axis=1)

In [151]:
# Defining the mapping for renaming the columns
rename_mapping = {
    '-': 'hyphen_probability',
    '.': 'dot_probability',
    '@': 'at_probability',
    ':': 'colon_probability',
    '=': 'equals_probability',
    '_': 'underscore_probability',
    '&': 'ampersand_probability',
    '#': 'hash_probability',
    '!': 'exclamation_probability',
    '+': 'plus_probability'
}

# Renaming the columns in the DataFrame
df = df.rename(columns=rename_mapping)

## 2.6.14 Frequent words in legitimats/phishing URLs

We will generate a list of continuous chunk of alphabets from both the legitimate and phishing urls. By substracting the legitimate list from the phishing list we will get a list of words that only appear in the phishing urls. We will then use the list to count how many times the words appear in a given url.

In [154]:
# Legitimate url dataset
dfl = df[df.status == 1]

In [155]:
# Phishing url dataset
dfp = df[df.status == 0]

In [156]:
legitimate_url = dfl['url'].tolist()

In [157]:
phishing_url = dfp['url'].tolist()

#### 2.6.14.1 Count of the words that only appear in phishing urls

In [159]:
def find_chunk(urls):
    '''A function to find continuous strings of alphabets'''
    chunk_counter = Counter()
    for url in urls:
        # First split the URL based on '/'
        segments = url.split('/')

        # Finding continuous chunks of words inside each segment
        for segment in segments:
            if segment.isalpha():
                
                # In case the segment contains only alphabets
                chunk_counter[segment.lower()] += 1
            else:
                
                # Extracting continuous chunks of alphabets
                chunks = re.findall(r'[a-zA-Z]+', segment) # The chunks may be separated by @, #, .,-, _, + etc.
                chunk_counter.update(chunk.lower() for chunk in chunks)
    
    return dict(chunk_counter)

In [160]:
legitimate_words = find_chunk(legitimate_url)

In [161]:
phishing_words = find_chunk(phishing_url)

In [162]:
common_words = set(phishing_words.keys()).intersection(legitimate_words.keys())

In [163]:
# Words that only appear in a phishing url
phi_url_exclusive = {key: phishing_words[key] for key in phishing_words if key not in common_words}

In [164]:
phi_url_exclusive_sorted = dict(sorted(phi_url_exclusive.items(), key=lambda item: item[1], reverse=True))

In [165]:
def match_words_and_count(url, word_list):
    ''' A function to extract chunk of alphabetic words from the URL and match with a list of words'''
    words_in_url = re.findall(r'[a-zA-Z]+', url.lower()) # It looks for chunks of alphabetic characters of any length.
    
    # Find matching words from a list of words 
    matched_words = [word for word in words_in_url if word in word_list]
    
    # Count the number of matched words
    match_word_count = len(matched_words)
    
    return matched_words, match_word_count

In [166]:
# Counting of the words that only appeared in the phishin urls
df[['matched_words_phi', 'matched_word_count_phi']] = df['url'].progress_apply(
    lambda url: pd.Series(match_words_and_count(url, phi_url_exclusive))
)

100%|████████████████████████████████████████████████████████████████████████| 807617/807617 [01:23<00:00, 9715.21it/s]

#### 2.6.14.2 Count of the words that appeared in legitimate/phishing urls

Finding all cotinuous chunks of alphabets in all urls

In [169]:
url_list = df['url'].tolist()

In [170]:
all_words = find_chunk(url_list)

In [171]:
df[['matched_words_all', 'matched_word_count_all']] = df['url'].progress_apply(
    lambda url: pd.Series(match_words_and_count(url, all_words))
)

100%|████████████████████████████████████████████████████████████████████████| 807617/807617 [01:26<00:00, 9319.29it/s]

#### 2.6.14.3 Sum of entropy of the words that appeared in legitimate/phishing urls

Calculating the entropy of the words in the 'matched_words_all'

In [174]:
def cal_word_entropy(words):
    if not words:
        return 0
    total_entropy = sum(calculate_entropy(word) for word in words)
    return total_entropy

In [175]:
df['words_entropy'] = df['matched_words_all'].progress_apply(cal_word_entropy)

100%|███████████████████████████████████████████████████████████████████████| 807617/807617 [01:02<00:00, 13012.24it/s]

In [176]:
df

,url,status,ext_host,tlds,len_url,len_host,len_tld,contains_ip,url_entropy,host_entropy,...,underscore_probability,ampersand_probability,hash_probability,exclamation_probability,plus_probability,matched_words_phi,matched_word_count_phi,matched_words_all,matched_word_count_all,words_entropy
0,0000111servicehelpdesk.godaddysites.com,0,0000111servicehelpdesk.godaddysites.com,com,39,39,3,0,4.045286,4.045286,...,0.0,0.0,0.0,0.0,0.0,"[servicehelpdesk, godaddysites]",2,"[servicehelpdesk, godaddysites, com]",3,7.847242
1,000011accesswebform.godaddysites.com,0,000011accesswebform.godaddysites.com,com,36,36,3,0,3.974938,3.974938,...,0.0,0.0,0.0,0.0,0.0,"[accesswebform, godaddysites]",2,"[accesswebform, godaddysites, com]",3,7.845919
2,00003.online,0,00003.online,online,12,12,6,0,2.751629,2.751629,...,0.0,0.0,0.0,0.0,0.0,[],0,[online],1,2.251629
3,0009servicedeskowa.godaddysites.com,0,0009servicedeskowa.godaddysites.com,com,35,35,3,0,3.943289,3.943289,...,0.0,0.0,0.0,0.0,0.0,"[servicedeskowa, godaddysites]",2,"[servicedeskowa, godaddysites, com]",3,7.931881
4,000n38p.wcomhost.com,0,000n38p.wcomhost.com,com,20,20,3,0,3.546439,3.546439,...,0.0,0.0,0.0,0.0,0.0,[wcomhost],1,"[n, p, wcomhost, com]",4,4.334963
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807612,zzufg.com,0,zzufg.com,com,9,9,3,0,2.947703,2.947703,...,0.0,0.0,0.0,0.0,0.0,[zzufg],1,"[zzufg, com]",2,3.506891
807613,zzu.li,0,zzu.li,li,6,6,2,0,2.251629,2.251629,...,0.0,0.0,0.0,0.0,0.0,[zzu],1,"[zzu, li]",2,1.918296
807614,zzz.co.uk,0,zzz.co.uk,uk,9,9,2,0,2.419382,2.419382,...,0.0,0.0,0.0,0.0,0.0,[],0,"[zzz, co, uk]",3,2.000000
807615,zzzoolight.co.za,0,zzzoolight.co.za,za,16,16,2,0,3.077820,3.077820,...,0.0,0.0,0.0,0.0,0.0,[zzzoolight],1,"[zzzoolight, co, za]",3,4.646439
807616,zzzoolight.co.za0-i-fdik.000webhostapp.com,0,zzzoolight.co.za0-i-fdik.000webhostapp.com,com,42,42,3,0,4.145543,4.145543,...,0.0,0.0,0.0,0.0,0.0,"[zzzoolight, fdik, webhostapp]",3,"[zzzoolight, co, za, i, fdik, webhostapp, com]",7,11.353330

#### 2.6.14.4 Count of the words that only appear in phishing ext_host

In [178]:
url_host = df['ext_host'].tolist()

In [179]:
url_legitimate = dfl['ext_host'].tolist()

In [180]:
url_phishing = dfp['ext_host'].tolist()

In [181]:
# Function to extract and count alphabet chunks
def count_alphabet_chunks(urls):
    word_counter = Counter()
    
    for url in urls:
        if isinstance(url, str):  # Ensure the URL is a string
            # Find all continuous chunks of alphabets using regex
            alphabet_chunks = re.findall(r'[a-zA-Z]+', url)
            
            # Update the counter with the found chunks
            word_counter.update(chunk.lower() for chunk in alphabet_chunks)
    
    return dict(word_counter)

In [182]:
# Get word frequency for legitimate url
alphabet_chunk_frequency_legitimate = count_alphabet_chunks(url_legitimate)

In [183]:
# Get word frequency for phishing url
alphabet_chunk_frequency_phishing = count_alphabet_chunks(url_phishing)

In [184]:
# Common words found both in legitimate and phishing urls
common_words_host = set(alphabet_chunk_frequency_legitimate.keys()).intersection(alphabet_chunk_frequency_phishing.keys())

In [185]:
# Removing common words
phishing_exclusive_words = {key: alphabet_chunk_frequency_phishing[key] for key in alphabet_chunk_frequency_phishing if key not in common_words_host }

In [186]:
# Sorting the dictionary
sorted_phi_exclu_words = dict(sorted(phishing_exclusive_words.items(), key=lambda item: item[1], reverse=True))

In [187]:
def match_words_and_count(url, word_list):
    ''' A function to extract chunk of alphabetic words from the URL and match with a list of words'''
    if isinstance(url, str):  # Check if url is a string
        words_in_url = re.findall(r'[a-zA-Z]+', url.lower())
        # Find matching words from a list of words 
        matched_words = [word for word in words_in_url if word in word_list]
        # Count the number of matched words
        match_word_count = len(matched_words)
    else:
        # Handle non-string or missing values
        matched_words = []
        match_word_count = 0
    
    return matched_words, match_word_count

In [188]:
# Count of the words that only appeared in the phishin ext_host
df[['matched_words_host_phi', 'matched_word_count_host_phi']] = df['ext_host'].progress_apply(
    lambda url: pd.Series(match_words_and_count(url, phishing_exclusive_words))
)

100%|████████████████████████████████████████████████████████████████████████| 807617/807617 [01:25<00:00, 9480.94it/s]

#### 2.6.15.5 Sum of entropy of the words that appeared in phishing ext_host

In [190]:
df['words_entropy_host_phi'] = df['matched_words_host_phi'].progress_apply(cal_word_entropy)

100%|███████████████████████████████████████████████████████████████████████| 807617/807617 [00:08<00:00, 90384.86it/s]

#### 2.6.15.6 Count of the words that only appear in legitimate/phishing ext_host

In [192]:
# Get word frequency for legitimate/phishing ext_host
alphabet_chunk_frequency_host = count_alphabet_chunks(url_host)

In [193]:
# Counting of the words that only appeared in the phishin ext_host
df[['matched_words_host', 'matched_word_count_host']] = df['ext_host'].progress_apply(
    lambda url: pd.Series(match_words_and_count(url, alphabet_chunk_frequency_host))
)

100%|████████████████████████████████████████████████████████████████████████| 807617/807617 [01:30<00:00, 8883.03it/s]

#### 2.6.15.7 Sum of entropy of the words that appeared in legitimate/phishing ext_host

In [195]:
df['words_entropy_host'] = df['matched_words_host'].progress_apply(cal_word_entropy)

100%|███████████████████████████████████████████████████████████████████████| 807617/807617 [00:28<00:00, 28468.50it/s]

## 2.6.15 Using NLTK corpus

In the Natural Language Toolkit (NLTK), a corpus refers to a collection of texts or datasets used for natural language processing (NLP) and computational linguistics. It provides a variety of text resources and datasets to help researchers and developers analyze and process human language.

Texts are collected from various sources, such as literary works, news articles, legal documents, or speech transcripts. Texts are standardized to ensure consistency (e.g., converting to lowercase, removing non-text content).

In this project we do not eploit the intricate features of the NLTK. We simply use the english words that are stored in the corpus to match the extracted words from the urls.

In [197]:
nltk.download('words')
# Getting the set of English words from NLTK corpus for faster lookup
english_words = set(words.words())

[nltk_data] Downloading package words to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!

In [198]:
df.head(1)

,url,status,ext_host,tlds,len_url,len_host,len_tld,contains_ip,url_entropy,host_entropy,...,matched_word_count_phi,matched_words_all,matched_word_count_all,words_entropy,matched_words_host_phi,matched_word_count_host_phi,words_entropy_host_phi,matched_words_host,matched_word_count_host,words_entropy_host
0,0000111servicehelpdesk.godaddysites.com,0,0000111servicehelpdesk.godaddysites.com,com,39,39,3,0,4.045286,4.045286,...,2,"[servicehelpdesk, godaddysites, com]",3,7.847242,"[servicehelpdesk, godaddysites]",2,6.262279,"[servicehelpdesk, godaddysites, com]",3,7.847242

#### 2.6.15.1 Common English words in url

In [200]:
df[['english_words_url', 'english_word_count_url']] = df['url'].progress_apply(
    lambda url: pd.Series(match_words_and_count(url, english_words))
)

100%|████████████████████████████████████████████████████████████████████████| 807617/807617 [01:29<00:00, 9003.08it/s]

In [201]:
df.describe()

,status,len_url,len_host,len_tld,contains_ip,url_entropy,host_entropy,tld_entropy,has_js,js_entropy,...,exclamation_probability,plus_probability,matched_word_count_phi,matched_word_count_all,words_entropy,matched_word_count_host_phi,words_entropy_host_phi,matched_word_count_host,words_entropy_host,english_word_count_url
count,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000,...,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000,807617.000000
mean,0.528291,44.258049,18.248422,2.854511,0.009766,4.005894,3.395090,1.478562,0.107496,0.358167,...,0.000013,0.000709,0.868601,6.801140,12.508715,0.595236,1.548380,2.829007,5.494194,2.427378
std,0.499199,42.058890,11.755529,0.595765,0.098338,0.488283,0.387204,0.276772,0.309744,1.066605,...,0.000655,0.006101,2.209176,6.817736,10.281215,0.888803,2.220556,2.085687,2.768484,3.707000
min,0.000000,2.000000,1.000000,1.000000,0.000000,-0.000000,-0.000000,-0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,22.000000,12.000000,3.000000,0.000000,3.708132,3.121928,1.584963,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.000000,6.735926,0.000000,0.000000,2.000000,4.169925,0.000000
50%,1.000000,34.000000,16.000000,3.000000,0.000000,4.027719,3.418296,1.584963,0.000000,0.000000,...,0.000000,0.000000,0.000000,5.000000,10.219938,0.000000,0.000000,2.000000,4.823864,1.000000
75%,1.000000,53.000000,21.000000,3.000000,0.000000,4.329971,3.641250,1.584963,0.000000,0.000000,...,0.000000,0.000000,1.000000,8.000000,15.148744,1.000000,2.921928,3.000000,6.218855,3.000000
max,1.000000,3985.000000,244.000000,121.000000,1.000000,6.011721,5.288846,4.940654,1.000000,5.977103,...,0.117647,0.312500,302.000000,480.000000,955.684033,27.000000,58.492483,78.000000,72.984336,180.000000

#### 2.6.15.2 Entropy of common English words in url

In [203]:
df['english_words_entropy_url'] = df['english_words_url'].progress_apply(cal_word_entropy)

100%|███████████████████████████████████████████████████████████████████████| 807617/807617 [00:19<00:00, 40701.96it/s]

#### 2.6.15.3 Common English words in host

In [205]:
df[['english_words_host', 'english_word_count_host']] = df['ext_host'].progress_apply(
    lambda url: pd.Series(match_words_and_count(url, english_words))
)

100%|████████████████████████████████████████████████████████████████████████| 807617/807617 [01:29<00:00, 9053.49it/s]

#### 2.6.15.4 Entropy of common English words in host

In [207]:
df['english_words_entropy_host'] = df['english_words_host'].progress_apply(cal_word_entropy)

100%|██████████████████████████████████████████████████████████████████████| 807617/807617 [00:05<00:00, 155871.07it/s]

In [208]:
df.select_dtypes(exclude=['number'])

,url,ext_host,tlds,query_js,dotnum_pat_3,url_random_substrings,host_random_substrings,host_segment_dot,special_char_probabilities,matched_words_phi,matched_words_all,matched_words_host_phi,matched_words_host,english_words_url,english_words_host
0,0000111servicehelpdesk.godaddysites.com,0000111servicehelpdesk.godaddysites.com,com,[],[],"[0000111servicehelpdesk, godaddysites, com]","[0000111servicehelpdesk, godaddysites, com]","[0000111servicehelpdesk, godaddysites, com]","{'-': 0.0, '.': 0.05128205128205128, '@': 0.0,...","[servicehelpdesk, godaddysites]","[servicehelpdesk, godaddysites, com]","[servicehelpdesk, godaddysites]","[servicehelpdesk, godaddysites, com]",[],[]
1,000011accesswebform.godaddysites.com,000011accesswebform.godaddysites.com,com,[],[],"[000011accesswebform, godaddysites, com]","[000011accesswebform, godaddysites, com]","[000011accesswebform, godaddysites, com]","{'-': 0.0, '.': 0.05555555555555555, '@': 0.0,...","[accesswebform, godaddysites]","[accesswebform, godaddysites, com]","[accesswebform, godaddysites]","[accesswebform, godaddysites, com]",[],[]
2,00003.online,00003.online,online,[],[],"[00003, online]","[00003, online]","[00003, online]","{'-': 0.0, '.': 0.08333333333333333, '@': 0.0,...",[],[online],[],[online],[],[]
3,0009servicedeskowa.godaddysites.com,0009servicedeskowa.godaddysites.com,com,[],[],"[0009servicedeskowa, godaddysites, com]","[0009servicedeskowa, godaddysites, com]","[0009servicedeskowa, godaddysites, com]","{'-': 0.0, '.': 0.05714285714285714, '@': 0.0,...","[servicedeskowa, godaddysites]","[servicedeskowa, godaddysites, com]","[servicedeskowa, godaddysites]","[servicedeskowa, godaddysites, com]",[],[]
4,000n38p.wcomhost.com,000n38p.wcomhost.com,com,[],[],"[000n38p, wcomhost, com]","[000n38p, wcomhost, com]","[000n38p, wcomhost, com]","{'-': 0.0, '.': 0.1, '@': 0.0, ':': 0.0, '=': ...",[wcomhost],"[n, p, wcomhost, com]",[wcomhost],"[n, p, wcomhost, com]","[n, p]","[n, p]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807612,zzufg.com,zzufg.com,com,[],[],"[zzufg, com]","[zzufg, com]","[zzufg, com]","{'-': 0.0, '.': 0.1111111111111111, '@': 0.0, ...",[zzufg],"[zzufg, com]",[zzufg],"[zzufg, com]",[],[]
807613,zzu.li,zzu.li,li,[],[],[zzu],[zzu],"[zzu, li]","{'-': 0.0, '.': 0.16666666666666666, '@': 0.0,...",[zzu],"[zzu, li]",[zzu],"[zzu, li]",[li],[li]
807614,zzz.co.uk,zzz.co.uk,uk,[],[],[zzz],[zzz],"[zzz, co, uk]","{'-': 0.0, '.': 0.2222222222222222, '@': 0.0, ...",[],"[zzz, co, uk]",[],"[zzz, co, uk]",[],[]
807615,zzzoolight.co.za,zzzoolight.co.za,za,[],[],[zzzoolight],[zzzoolight],"[zzzoolight, co, za]","{'-': 0.0, '.': 0.125, '@': 0.0, ':': 0.0, '='...",[zzzoolight],"[zzzoolight, co, za]",[zzzoolight],"[zzzoolight, co, za]",[za],[za]
807616,zzzoolight.co.za0-i-fdik.000webhostapp.com,zzzoolight.co.za0-i-fdik.000webhostapp.com,com,[],[],"[zzzoolight, za0, fdik, 000webhostapp, com]","[zzzoolight, za0, fdik, 000webhostapp, com]","[zzzoolight, co, za0-i-fdik, 000webhostapp, com]","{'-': 0.047619047619047616, '.': 0.09523809523...","[zzzoolight, fdik, webhostapp]","[zzzoolight, co, za, i, fdik, webhostapp, com]","[zzzoolight, fdik, webhostapp]","[zzzoolight, co, za, i, fdik, webhostapp, com]","[za, i]","[za, i]"

# 2.7 Saving the file

In [210]:
df.to_csv('../data/interim/df_exploratory_interim_full.csv')

In [211]:
df.select_dtypes(exclude=['number'])

,url,ext_host,tlds,query_js,dotnum_pat_3,url_random_substrings,host_random_substrings,host_segment_dot,special_char_probabilities,matched_words_phi,matched_words_all,matched_words_host_phi,matched_words_host,english_words_url,english_words_host
0,0000111servicehelpdesk.godaddysites.com,0000111servicehelpdesk.godaddysites.com,com,[],[],"[0000111servicehelpdesk, godaddysites, com]","[0000111servicehelpdesk, godaddysites, com]","[0000111servicehelpdesk, godaddysites, com]","{'-': 0.0, '.': 0.05128205128205128, '@': 0.0,...","[servicehelpdesk, godaddysites]","[servicehelpdesk, godaddysites, com]","[servicehelpdesk, godaddysites]","[servicehelpdesk, godaddysites, com]",[],[]
1,000011accesswebform.godaddysites.com,000011accesswebform.godaddysites.com,com,[],[],"[000011accesswebform, godaddysites, com]","[000011accesswebform, godaddysites, com]","[000011accesswebform, godaddysites, com]","{'-': 0.0, '.': 0.05555555555555555, '@': 0.0,...","[accesswebform, godaddysites]","[accesswebform, godaddysites, com]","[accesswebform, godaddysites]","[accesswebform, godaddysites, com]",[],[]
2,00003.online,00003.online,online,[],[],"[00003, online]","[00003, online]","[00003, online]","{'-': 0.0, '.': 0.08333333333333333, '@': 0.0,...",[],[online],[],[online],[],[]
3,0009servicedeskowa.godaddysites.com,0009servicedeskowa.godaddysites.com,com,[],[],"[0009servicedeskowa, godaddysites, com]","[0009servicedeskowa, godaddysites, com]","[0009servicedeskowa, godaddysites, com]","{'-': 0.0, '.': 0.05714285714285714, '@': 0.0,...","[servicedeskowa, godaddysites]","[servicedeskowa, godaddysites, com]","[servicedeskowa, godaddysites]","[servicedeskowa, godaddysites, com]",[],[]
4,000n38p.wcomhost.com,000n38p.wcomhost.com,com,[],[],"[000n38p, wcomhost, com]","[000n38p, wcomhost, com]","[000n38p, wcomhost, com]","{'-': 0.0, '.': 0.1, '@': 0.0, ':': 0.0, '=': ...",[wcomhost],"[n, p, wcomhost, com]",[wcomhost],"[n, p, wcomhost, com]","[n, p]","[n, p]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807612,zzufg.com,zzufg.com,com,[],[],"[zzufg, com]","[zzufg, com]","[zzufg, com]","{'-': 0.0, '.': 0.1111111111111111, '@': 0.0, ...",[zzufg],"[zzufg, com]",[zzufg],"[zzufg, com]",[],[]
807613,zzu.li,zzu.li,li,[],[],[zzu],[zzu],"[zzu, li]","{'-': 0.0, '.': 0.16666666666666666, '@': 0.0,...",[zzu],"[zzu, li]",[zzu],"[zzu, li]",[li],[li]
807614,zzz.co.uk,zzz.co.uk,uk,[],[],[zzz],[zzz],"[zzz, co, uk]","{'-': 0.0, '.': 0.2222222222222222, '@': 0.0, ...",[],"[zzz, co, uk]",[],"[zzz, co, uk]",[],[]
807615,zzzoolight.co.za,zzzoolight.co.za,za,[],[],[zzzoolight],[zzzoolight],"[zzzoolight, co, za]","{'-': 0.0, '.': 0.125, '@': 0.0, ':': 0.0, '='...",[zzzoolight],"[zzzoolight, co, za]",[zzzoolight],"[zzzoolight, co, za]",[za],[za]
807616,zzzoolight.co.za0-i-fdik.000webhostapp.com,zzzoolight.co.za0-i-fdik.000webhostapp.com,com,[],[],"[zzzoolight, za0, fdik, 000webhostapp, com]","[zzzoolight, za0, fdik, 000webhostapp, com]","[zzzoolight, co, za0-i-fdik, 000webhostapp, com]","{'-': 0.047619047619047616, '.': 0.09523809523...","[zzzoolight, fdik, webhostapp]","[zzzoolight, co, za, i, fdik, webhostapp, com]","[zzzoolight, fdik, webhostapp]","[zzzoolight, co, za, i, fdik, webhostapp, com]","[za, i]","[za, i]"

In [212]:
# List of object type columns to delete
columns_to_delete = [
    'query_js', 'dotnum_pat_3', 'url_random_substrings', 'host_random_substrings',
    'host_segment_dot', 'special_char_probabilities', 'matched_words_phi',
    'matched_words_all', 'matched_words_host_phi', 'matched_words_host',
    'english_words_url', 'english_words_host'
]
df_num = df.drop(columns=columns_to_delete)

In [213]:
df_num.to_csv('../data/interim/df_exploratory_interim_numeric.csv')

In [214]:
df = pd.read_csv('../data/interim/df_exploratory_interim_full.csv', index_col=0)
df.head()

,url,status,ext_host,tlds,len_url,len_host,len_tld,contains_ip,url_entropy,host_entropy,...,words_entropy_host_phi,matched_words_host,matched_word_count_host,words_entropy_host,english_words_url,english_word_count_url,english_words_entropy_url,english_words_host,english_word_count_host,english_words_entropy_host
0,0000111servicehelpdesk.godaddysites.com,0,0000111servicehelpdesk.godaddysites.com,com,39,39,3,0,4.045286,4.045286,...,6.262279,"['servicehelpdesk', 'godaddysites', 'com']",3,7.847242,[],0,0.0,[],0,0.0
1,000011accesswebform.godaddysites.com,0,000011accesswebform.godaddysites.com,com,36,36,3,0,3.974938,3.974938,...,6.260956,"['accesswebform', 'godaddysites', 'com']",3,7.845919,[],0,0.0,[],0,0.0
2,00003.online,0,00003.online,online,12,12,6,0,2.751629,2.751629,...,0.000000,['online'],1,2.251629,[],0,0.0,[],0,0.0
3,0009servicedeskowa.godaddysites.com,0,0009servicedeskowa.godaddysites.com,com,35,35,3,0,3.943289,3.943289,...,6.346918,"['servicedeskowa', 'godaddysites', 'com']",3,7.931881,[],0,0.0,[],0,0.0
4,000n38p.wcomhost.com,0,000n38p.wcomhost.com,com,20,20,3,0,3.546439,3.546439,...,2.750000,"['n', 'p', 'wcomhost', 'com']",4,4.334963,"['n', 'p']",2,0.0,"['n', 'p']",2,0.0

In [215]:
df.shape

(807617, 70)

In [216]:
df.isnull().sum()

url                           0
status                        0
ext_host                      0
tlds                          0
len_url                       0
                             ..
english_word_count_url        0
english_words_entropy_url     0
english_words_host            0
english_word_count_host       0
english_words_entropy_host    0
Length: 70, dtype: int64

In [217]:
df.ext_host.isnull().sum()

0

In [218]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [url, status, ext_host, tlds, len_url, len_host, len_tld, contains_ip, url_entropy, host_entropy, tld_entropy, has_js, query_js, js_entropy, dotnum_pat_3, num_pat_3, pat_3_entropy, host_len_capital, host_ratio_capital, url_len_capital, url_ratio_capital, url_char_num_ratio, url_spe_char_ratio, host_char_num_ratio, host_spe_char_ratio, url_obfuscation_status, host_obfuscation_status, obfuscation_entropy_url, obfuscation_entropy_host, url_random_substrings, url_sub_entropy, host_random_substrings, host_sub_entropy, n_hypens, n_uscores, n_semicolon, n_equal_sign, n_plus_sign, num_segments_host, host_segment_dot, host_segment_entropy, tld_fuzzy_score, special_char_probabilities, hyphen_probability, dot_probability, at_probability, colon_probability, equals_probability, underscore_probability, ampersand_probability, hash_probability, exclamation_probability, plus_probability, matched_words_phi, matched_word_count_phi, matched_words_all, matched_word_count_all, words_entropy, matched_words_host_phi, matched_word_count_host_phi, words_entropy_host_phi, matched_words_host, matched_word_count_host, words_entropy_host, english_words_url, english_word_count_url, english_words_entropy_url, english_words_host, english_word_count_host, english_words_entropy_host]
Index: []

[0 rows x 70 columns]

In [219]:
df.reset_index(drop=True, inplace=True)

# 2.8 TF-IDF

In [220]:
vectorizer = TfidfVectorizer(analyzer='char', use_idf=False, norm='l1', ngram_range=(1, 1))
#analyzer='char': This treats each character as a feature instead of words. This is useful for processing hostnames (ext_host), URLs, 
# or strings that may have a pattern based on individual characters.
# use_idf=False: Disables the use of the inverse document frequency (IDF). Only raw term frequencies will be used.
# norm='l1': Ensures that the feature vectors are normalized using the L1 norm (i.e., the sum of absolute values of vector elements equals 1).
#ngram_range=(1, 1): Considers only single characters (unigrams) as features.

tfidf_matrix = vectorizer.fit_transform(df['ext_host'])

svd = TruncatedSVD(n_components=30)

reduced_tfidf = svd.fit_transform(tfidf_matrix)

df_tfidf_reduced = pd.DataFrame(reduced_tfidf)

# Measures how much of the total variance in the original high-dimensional data is preserved by the 30 components.
svd.explained_variance_ratio_.sum()

0.9771145237179982

In [221]:
df_tfidf_reduced

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,0.181830,0.070040,-0.039373,-0.013287,0.031873,0.048550,-0.021843,-0.045628,0.024870,-0.034774,...,0.005826,-0.049417,-0.027416,0.039917,0.007079,-0.035769,0.017461,0.000264,0.062355,-0.067776
1,0.202595,0.003080,-0.012277,-0.032882,0.015522,0.047409,-0.010660,-0.039910,0.040877,-0.006096,...,0.015174,-0.004156,-0.050509,0.034133,0.008651,-0.030207,0.015308,0.002149,0.077238,-0.056443
2,0.160610,0.074985,-0.014345,0.104589,0.007504,-0.025024,0.025381,0.079604,0.019482,-0.083630,...,-0.022935,-0.024552,-0.043719,0.040542,0.016065,-0.025851,0.006996,0.015157,0.308779,-0.047114
3,0.205878,0.050743,-0.023568,-0.014965,0.007165,0.034126,-0.020436,-0.046987,0.050083,-0.013372,...,0.031172,-0.012758,-0.013727,0.032507,0.006157,-0.020418,0.008295,0.001386,0.075320,-0.014096
4,0.211213,-0.104047,-0.032317,0.015467,-0.015273,0.036280,0.048496,0.019897,0.015903,-0.019564,...,-0.024271,0.023219,-0.031303,0.032037,0.003863,-0.019301,-0.000738,0.004432,0.132839,-0.015229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807612,0.197672,-0.114562,-0.013513,0.036896,0.005031,0.067405,-0.025182,0.043083,-0.031253,0.013941,...,-0.010650,0.038739,0.030363,-0.058311,0.154795,-0.106701,-0.021234,-0.070761,-0.004019,-0.003512
807613,0.147398,0.064678,0.045328,0.142044,-0.003511,0.082402,0.001910,-0.040660,-0.154267,-0.073407,...,0.001992,0.040599,0.092184,-0.134816,0.234693,-0.128447,-0.034074,-0.100799,0.000594,-0.005887
807614,0.200732,-0.078514,0.003318,0.062847,-0.005889,0.151990,-0.024420,0.088511,-0.059968,0.005602,...,0.013727,-0.000706,0.099419,-0.135198,0.222419,-0.124045,-0.050149,-0.101799,0.001521,-0.007653
807615,0.219431,-0.062359,0.011904,0.044240,-0.095659,-0.007365,0.004095,0.032839,-0.054878,-0.037337,...,0.008991,0.005259,0.064818,-0.103248,0.176011,-0.095208,-0.027433,-0.073401,-0.002623,-0.003417
807616,0.188465,-0.020173,0.004402,0.037147,-0.045164,0.013269,0.002879,-0.007015,-0.037217,-0.035612,...,-0.016032,0.004908,0.001809,-0.003053,0.091675,-0.023138,-0.030011,-0.027625,0.078923,-0.022534

In [222]:
df_tfidf_reduced.shape

(807617, 30)

In [223]:
df_tf_idf = pd.concat([df, df_tfidf_reduced], axis=1)

In [224]:
df_tf_idf

,url,status,ext_host,tlds,len_url,len_host,len_tld,contains_ip,url_entropy,host_entropy,...,20,21,22,23,24,25,26,27,28,29
0,0000111servicehelpdesk.godaddysites.com,0,0000111servicehelpdesk.godaddysites.com,com,39,39,3,0,4.045286,4.045286,...,0.005826,-0.049417,-0.027416,0.039917,0.007079,-0.035769,0.017461,0.000264,0.062355,-0.067776
1,000011accesswebform.godaddysites.com,0,000011accesswebform.godaddysites.com,com,36,36,3,0,3.974938,3.974938,...,0.015174,-0.004156,-0.050509,0.034133,0.008651,-0.030207,0.015308,0.002149,0.077238,-0.056443
2,00003.online,0,00003.online,online,12,12,6,0,2.751629,2.751629,...,-0.022935,-0.024552,-0.043719,0.040542,0.016065,-0.025851,0.006996,0.015157,0.308779,-0.047114
3,0009servicedeskowa.godaddysites.com,0,0009servicedeskowa.godaddysites.com,com,35,35,3,0,3.943289,3.943289,...,0.031172,-0.012758,-0.013727,0.032507,0.006157,-0.020418,0.008295,0.001386,0.075320,-0.014096
4,000n38p.wcomhost.com,0,000n38p.wcomhost.com,com,20,20,3,0,3.546439,3.546439,...,-0.024271,0.023219,-0.031303,0.032037,0.003863,-0.019301,-0.000738,0.004432,0.132839,-0.015229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807612,zzufg.com,0,zzufg.com,com,9,9,3,0,2.947703,2.947703,...,-0.010650,0.038739,0.030363,-0.058311,0.154795,-0.106701,-0.021234,-0.070761,-0.004019,-0.003512
807613,zzu.li,0,zzu.li,li,6,6,2,0,2.251629,2.251629,...,0.001992,0.040599,0.092184,-0.134816,0.234693,-0.128447,-0.034074,-0.100799,0.000594,-0.005887
807614,zzz.co.uk,0,zzz.co.uk,uk,9,9,2,0,2.419382,2.419382,...,0.013727,-0.000706,0.099419,-0.135198,0.222419,-0.124045,-0.050149,-0.101799,0.001521,-0.007653
807615,zzzoolight.co.za,0,zzzoolight.co.za,za,16,16,2,0,3.077820,3.077820,...,0.008991,0.005259,0.064818,-0.103248,0.176011,-0.095208,-0.027433,-0.073401,-0.002623,-0.003417
807616,zzzoolight.co.za0-i-fdik.000webhostapp.com,0,zzzoolight.co.za0-i-fdik.000webhostapp.com,com,42,42,3,0,4.145543,4.145543,...,-0.016032,0.004908,0.001809,-0.003053,0.091675,-0.023138,-0.030011,-0.027625,0.078923,-0.022534

In [225]:
df_tf_idf[df_tf_idf.isnull().any(axis=1)]

Empty DataFrame
Columns: [url, status, ext_host, tlds, len_url, len_host, len_tld, contains_ip, url_entropy, host_entropy, tld_entropy, has_js, query_js, js_entropy, dotnum_pat_3, num_pat_3, pat_3_entropy, host_len_capital, host_ratio_capital, url_len_capital, url_ratio_capital, url_char_num_ratio, url_spe_char_ratio, host_char_num_ratio, host_spe_char_ratio, url_obfuscation_status, host_obfuscation_status, obfuscation_entropy_url, obfuscation_entropy_host, url_random_substrings, url_sub_entropy, host_random_substrings, host_sub_entropy, n_hypens, n_uscores, n_semicolon, n_equal_sign, n_plus_sign, num_segments_host, host_segment_dot, host_segment_entropy, tld_fuzzy_score, special_char_probabilities, hyphen_probability, dot_probability, at_probability, colon_probability, equals_probability, underscore_probability, ampersand_probability, hash_probability, exclamation_probability, plus_probability, matched_words_phi, matched_word_count_phi, matched_words_all, matched_word_count_all, words_entropy, matched_words_host_phi, matched_word_count_host_phi, words_entropy_host_phi, matched_words_host, matched_word_count_host, words_entropy_host, english_words_url, english_word_count_url, english_words_entropy_url, english_words_host, english_word_count_host, english_words_entropy_host, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
Index: []

[0 rows x 100 columns]

In [226]:
df_tf_idf.to_csv('../data/interim/df_exploratory_interim_tf_idf.csv')